# Generated by Django 4.0.3 on 2022-03-06 10:26

import apps.utils.filesize
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='сюда загружаем фото в формате JPG или PNG.\n МАКСИМАЛЬНЫЙ РАЗМЕР 1MB(мегабайт), чтобы не заполнять память хостинга', null=True, upload_to='gallery/', validators=[apps.utils.filesize.file_size], verbose_name='Фото галереи')),
            ],
            options={
                'verbose_name': 'галерея',
                'verbose_name_plural': 'Галерея',
            },
        ),
        migrations.CreateModel(
            name='InisiativMiniProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Название')),
                ('project_desc', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание №1')),
                ('video', models.CharField(blank=True, help_text='сюда нужно поставить ссылку на видео из YouTube. Например: https://www.youtube-nocookie.com/embed/tGTUTXYDhb8?controls=0 ', max_length=255, null=True, verbose_name='Видео проекта')),
                ('image', models.ImageField(blank=True, help_text='сюда загружаем фото в формате JPG или PNG.\n МАКСИМАЛЬНЫЙ РАЗМЕР 1MB(мегабайт), чтобы не заполнять память хостинга', null=True, upload_to='projects/', validators=[apps.utils.filesize.file_size], verbose_name='Фото проекта')),
                ('purpose', models.TextField(blank=True, null=True, verbose_name='Описание цели проекта')),
                ('members', models.TextField(blank=True, null=True, verbose_name='Участники проекта')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Инициативы и Мини проекты',
                'verbose_name_plural': 'Инициативы и Мини проекты',
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название партнеров')),
                ('part_desc', models.TextField(verbose_name='Описание партнеров')),
                ('logo', models.ImageField(blank=True, help_text='сюда загружаем фото в формате JPG или PNG.\n МАКСИМАЛЬНЫЙ РАЗМЕР 1MB(мегабайт), чтобы не заполнять память хостинга', null=True, upload_to='partners/', validators=[apps.utils.filesize.file_size])),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
            options={
                'verbose_name': 'партнёр',
                'verbose_name_plural': 'Партнёры',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='Название проекта')),
                ('project_desc', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание баннера №1')),
                ('video', models.CharField(blank=True, help_text='сюда нужно поставить ссылку на видео из YouTube. Например: https://www.youtube-nocookie.com/embed/tGTUTXYDhb8?controls=0 ', max_length=255, null=True, verbose_name='Видео проекта')),
                ('image', models.ImageField(blank=True, help_text='сюда загружаем фото в формате JPG или PNG.\n МАКСИМАЛЬНЫЙ РАЗМЕР 1MB(мегабайт), чтобы не заполнять память хостинга', null=True, upload_to='projects/', validators=[apps.utils.filesize.file_size], verbose_name='Фото проекта')),
                ('purpose', models.TextField(blank=True, null=True, verbose_name='Описание цели проекта')),
                ('members', models.TextField(blank=True, null=True, verbose_name='Участники проекта')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'Проекты',
            },
        ),
        migrations.CreateModel(
            name='ProjectsPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='сюда загружаем фото в формате JPG или PNG.\n МАКСИМАЛЬНЫЙ РАЗМЕР 1MB(мегабайт), чтобы не заполнять память хостинга', upload_to='projects/', validators=[apps.utils.filesize.file_size], verbose_name='Фото проекта')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projects', verbose_name='К какому проекту относится')),
            ],
            options={
                'verbose_name': 'фото проекта',
                'verbose_name_plural': 'Фото проекта',
            },
        ),
    ]
