# Generated by Django 4.0.3 on 2022-03-21 08:34

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inisiativminiprojects',
            name='members_en',
            field=models.TextField(blank=True, null=True, verbose_name='Участники проекта'),
        ),
        migrations.AddField(
            model_name='inisiativminiprojects',
            name='members_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Участники проекта'),
        ),
        migrations.AddField(
            model_name='inisiativminiprojects',
            name='project_desc_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание №1'),
        ),
        migrations.AddField(
            model_name='inisiativminiprojects',
            name='project_desc_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание №1'),
        ),
        migrations.AddField(
            model_name='inisiativminiprojects',
            name='purpose_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание цели проекта'),
        ),
        migrations.AddField(
            model_name='inisiativminiprojects',
            name='purpose_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание цели проекта'),
        ),
        migrations.AddField(
            model_name='inisiativminiprojects',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='inisiativminiprojects',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='partners',
            name='part_desc_en',
            field=models.TextField(null=True, verbose_name='Описание партнеров'),
        ),
        migrations.AddField(
            model_name='partners',
            name='part_desc_ru',
            field=models.TextField(null=True, verbose_name='Описание партнеров'),
        ),
        migrations.AddField(
            model_name='partners',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название партнеров'),
        ),
        migrations.AddField(
            model_name='partners',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название партнеров'),
        ),
        migrations.AddField(
            model_name='projects',
            name='members_en',
            field=models.TextField(blank=True, null=True, verbose_name='Участники проекта'),
        ),
        migrations.AddField(
            model_name='projects',
            name='members_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Участники проекта'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_desc_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание баннера №1'),
        ),
        migrations.AddField(
            model_name='projects',
            name='project_desc_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание баннера №1'),
        ),
        migrations.AddField(
            model_name='projects',
            name='purpose_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание цели проекта'),
        ),
        migrations.AddField(
            model_name='projects',
            name='purpose_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание цели проекта'),
        ),
        migrations.AddField(
            model_name='projects',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Название проекта'),
        ),
        migrations.AddField(
            model_name='projects',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Название проекта'),
        ),
    ]
