# Generated by Django 4.0.3 on 2022-03-06 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название oбучение')),
            ],
            options={
                'verbose_name': 'Обучение',
                'verbose_name_plural': 'Обучение',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_servey', to='educations.courses')),
            ],
            options={
                'verbose_name': 'Опрос',
                'verbose_name_plural': 'Опрос',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_test', to='educations.courses')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='WorkSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('file', models.FileField(blank=True, null=True, upload_to='worksheet_pdf', verbose_name='Рабочая Тетрадь')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_worksheet', to='educations.courses')),
            ],
            options={
                'verbose_name': 'Рабочая Тетрадь',
                'verbose_name_plural': 'Рабочии Тетради',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=255, null=True)),
                ('answer', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_answer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Вопрос Теста')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_question', to='educations.test')),
            ],
            options={
                'verbose_name': 'Вопрос Теста',
                'verbose_name_plural': 'Вопросы Теста',
            },
        ),
        migrations.CreateModel(
            name='TestAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Ответ Теста')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_answer', to='educations.testquestion')),
            ],
            options={
                'verbose_name': 'Ответ Теста',
                'verbose_name_plural': 'Ответы Теста',
            },
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True, null=True, verbose_name='Вопрос Опроса')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_question', to='educations.survey')),
            ],
            options={
                'verbose_name': 'Вопрос Опроса',
                'verbose_name_plural': 'Вопросы Опроса',
            },
        ),
        migrations.CreateModel(
            name='SurveyAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='Ответ Опроса')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_answer', to='educations.surveyquestion')),
            ],
            options={
                'verbose_name': 'Ответ Опроса',
                'verbose_name_plural': 'Ответы Опроса',
            },
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_statistics', to='educations.courses')),
            ],
            options={
                'verbose_name': 'Статистика ЦА',
                'verbose_name_plural': 'Статистика ЦА',
            },
        ),
        migrations.CreateModel(
            name='StatisticImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='statistic_image/', verbose_name='Изображение Статистики')),
                ('statistic_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistic_image', to='educations.statistics')),
            ],
            options={
                'verbose_name': 'Изображение Статистики',
                'verbose_name_plural': 'Изображения Статстики',
            },
        ),
        migrations.CreateModel(
            name='Laws',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_laws', to='educations.courses')),
            ],
            options={
                'verbose_name': 'Законы КР о Гендерной Политике',
                'verbose_name_plural': 'Законы КР о Гендерной Политике',
            },
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('image', models.ImageField(blank=True, null=True, upload_to='introduction_image/', verbose_name='Изображение')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_intro', to='educations.courses')),
            ],
            options={
                'verbose_name': 'Введение',
                'verbose_name_plural': 'Введение',
            },
        ),
        migrations.CreateModel(
            name='GenderQuality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_gender_quality', to='educations.courses')),
            ],
            options={
                'verbose_name': 'Способы Продвижения Гендерного Равенства',
                'verbose_name_plural': 'Способы Продвижения Гендерного Равенства',
            },
        ),
        migrations.CreateModel(
            name='GenderNormStereotypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_gender_norm', to='educations.courses')),
            ],
            options={
                'verbose_name': 'Гендерные Стериотипы',
                'verbose_name_plural': 'Гендерные Стериотипы',
            },
        ),
        migrations.CreateModel(
            name='GenderNorms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_gender_norms', to='educations.courses')),
            ],
            options={
                'verbose_name': 'Гендерные Нормы',
                'verbose_name_plural': 'Гендерные Нормы',
            },
        ),
        migrations.CreateModel(
            name='GenderDiscrimination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_gender_discrim', to='educations.courses')),
            ],
            options={
                'verbose_name': 'Гендерная Дискриминация',
                'verbose_name_plural': 'Гендерная Дискриминация',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_gender', to='educations.courses')),
            ],
            options={
                'verbose_name': 'Гендер и Пол',
                'verbose_name_plural': 'Гендер и Пол',
            },
        ),
        migrations.CreateModel(
            name='EducationVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('video', models.FileField(blank=True, null=True, upload_to='video_education/', verbose_name='Видео с обучениями')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_edus', to='educations.courses')),
            ],
            options={
                'verbose_name': 'Видео с Обучениями',
                'verbose_name_plural': 'Видео с Обучениями',
            },
        ),
    ]
