# Generated by Django 4.0.3 on 2022-03-21 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_harassment'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='banner_title_1_en',
            field=models.CharField(blank=True, max_length=233, null=True, verbose_name='Заголовок баннера №1'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='banner_title_1_ru',
            field=models.CharField(blank=True, max_length=233, null=True, verbose_name='Заголовок баннера №1'),
        ),
        migrations.AddField(
            model_name='harassment',
            name='banner_title_1_en',
            field=models.CharField(blank=True, max_length=233, null=True, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='harassment',
            name='banner_title_1_ru',
            field=models.CharField(blank=True, max_length=233, null=True, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='setting',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Пара слов для поиска'),
        ),
        migrations.AddField(
            model_name='setting',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Пара слов для поиска'),
        ),
        migrations.AddField(
            model_name='setting',
            name='keywords_en',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Ключевые слова для поиска'),
        ),
        migrations.AddField(
            model_name='setting',
            name='keywords_ru',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Ключевые слова для поиска'),
        ),
        migrations.AddField(
            model_name='setting',
            name='title_en',
            field=models.CharField(max_length=150, null=True, verbose_name='Название сайта'),
        ),
        migrations.AddField(
            model_name='setting',
            name='title_ru',
            field=models.CharField(max_length=150, null=True, verbose_name='Название сайта'),
        ),
    ]
