# Generated by Django 4.0.3 on 2022-03-21 09:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_aboutus_banner_title_1_en_aboutus_banner_title_1_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='banner_desc_1_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание баннера №1'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='banner_desc_1_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание баннера №1'),
        ),
        migrations.AddField(
            model_name='harassment',
            name='harassment_desc_en',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание харассмента'),
        ),
        migrations.AddField(
            model_name='harassment',
            name='harassment_desc_ru',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание харассмента'),
        ),
    ]
